CSS:
  svg: css.svg
  link: https://www.w3.org/Style/CSS/
PostCSS:
  svg: postcss.svg
  link: https://postcss.org/docs/
SASS: 
  svg: sass.svg
  link: https://sass-lang.com/documentation/
Stylus: 
  svg: stylus.svg
  link: https://stylus-lang.com/
Less: 
  svg: less.svg
  link: https://lesscss.org/

HTML5: 
  svg: html.svg
  link: https://html.spec.whatwg.org/multipage/
Pug: 
  svg: pug.svg
  link: https://pugjs.org/api/getting-started.html

JavaScript: 
  svg: javascript-1.svg
  link: https://ecma-international.org/publications-and-standards/standards/
TypeScript: 
  svg: typescript.svg
  link: https://www.typescriptlang.org/docs/
Vue: 
  svg: vue.svg
  link: https://vuejs.org/
Babel: 
  svg: babel.svg
  link: https://babeljs.io/docs/
Prettier: 
  svg: prettier.svg
  link: https://prettier.io/
Eslint: 
  svg: eslint.svg
  link: https://eslint.org/docs/latest/

React: 
  svg: react.svg
  link: https://react.dev/
"React Query":
  svg: react-query.svg
  link: https://tanstack.com/query/latest/docs/framework/react/overview

Vite: 
  svg: vitejs.svg
  link: https://vitejs.dev/
Webpack: 
  svg: webpack.svg
  link: https://webpack.js.org/
NPM: 
  svg: npm.svg
  link: https://docs.npmjs.com/
Yarn:
  svg: yarn.svg
  link: https://classic.yarnpkg.com/en/
Gulp: 
  svg: gulp.svg
  link: https://gulpjs.com/
Grunt: 
  svg: grunt.svg
  link: https://gruntjs.com/getting-started

PostgreSQL: 
  svg: postgresql.svg
  link: https://www.postgresql.org/docs/
DBeaver: 
  svg: dbeaver.svg
  link: https://dbeaver.com/docs/dbeaver/
Ruby: 
  svg: ruby.svg
  link: https://ruby-doc.org/

Git: 
  svg: git.svg
  link: https://www.git-scm.com/doc
"Visual Studio Code": 
  svg: visual-studio-code.svg
  link: https://code.visualstudio.com/docs
ChatGPT: 
  svg: chatgpt.svg
  link: https://chatgpt.com/auth/login
conEmu:
  svg: conemu.svg
  link: 'https://conemu.github.io/blog/2023/07/24/Build-230724.html'

D3: 
  svg: d3.svg
  link: https://d3js.org/
Docker: 
  svg: docker.svg
  link: https://docs.docker.com/
Vagrant: 
  svg: vagrant.svg
  link: https://developer.hashicorp.com/vagrant/docs
VirtualBox: 
  svg: virtualbox.svg
  link: https://www.virtualbox.org/

# - 👋 Hi, I’m @AndriiKot
# - 👀 I’m interested in Frontend Development
# - 🌱 I’m currently React, Vue, PostgreSQL

# <!---
# AndriiKot/AndriiKot is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
# You can click the Preview link to take a look at your changes.
# --->

# # My Main TOOLS:

